// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Lease struct {
	ID              int64          `json:"id"`
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	Generation      int64          `json:"generation"`
	State           string         `json:"state"`
	SnapshotCommit  sql.NullString `json:"snapshot_commit"`
	BaseCommit      sql.NullString `json:"base_commit"`
	PushToken       sql.NullString `json:"push_token"`
	UpdatedAt       string         `json:"updated_at"`
}

type Replica struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	CreatedAt  string         `json:"created_at"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
}

type Workspace struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	DefaultBranch string `json:"default_branch"`
	CreatedAt     string `json:"created_at"`
}
