// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const archiveWorkspace = `-- name: ArchiveWorkspace :one
UPDATE workspaces SET archived_at = ? WHERE id = ? RETURNING id, name, default_branch, created_at, archived_at
`

type ArchiveWorkspaceParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) ArchiveWorkspace(ctx context.Context, arg ArchiveWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, archiveWorkspace, arg.ArchivedAt, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createHeldLease = `-- name: CreateHeldLease :one
INSERT INTO leases (workspace_id, branch, holder_replica_id, generation, state, push_token, expires_at)
VALUES (?, ?, ?, 1, 'held', ?, ?)
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation
`

type CreateHeldLeaseParams struct {
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	PushToken       sql.NullString `json:"push_token"`
	ExpiresAt       sql.NullInt64  `json:"expires_at"`
}

func (q *Queries) CreateHeldLease(ctx context.Context, arg CreateHeldLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, createHeldLease,
		arg.WorkspaceID,
		arg.Branch,
		arg.HolderReplicaID,
		arg.PushToken,
		arg.ExpiresAt,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, default_branch)
VALUES (?, ?)
RETURNING id, name, default_branch, created_at, archived_at
`

type CreateWorkspaceParams struct {
	Name          string `json:"name"`
	DefaultBranch string `json:"default_branch"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.DefaultBranch)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getLease = `-- name: GetLease :one
SELECT id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation FROM leases WHERE workspace_id = ? AND branch = ?
`

type GetLeaseParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Branch      string `json:"branch"`
}

func (q *Queries) GetLease(ctx context.Context, arg GetLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLease, arg.WorkspaceID, arg.Branch)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const getWorkspaceAnyByName = `-- name: GetWorkspaceAnyByName :one
SELECT id, name, default_branch, created_at, archived_at FROM workspaces WHERE name = ?
`

func (q *Queries) GetWorkspaceAnyByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAnyByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, default_branch, created_at, archived_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, default_branch, created_at, archived_at FROM workspaces WHERE name = ? AND archived_at IS NULL
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const grantLease = `-- name: GrantLease :one
UPDATE leases
SET holder_replica_id = ?,
    generation = generation + 1,
    state = 'held',
    push_token = ?,
    expires_at = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation
`

type GrantLeaseParams struct {
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	PushToken       sql.NullString `json:"push_token"`
	ExpiresAt       sql.NullInt64  `json:"expires_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) GrantLease(ctx context.Context, arg GrantLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, grantLease,
		arg.HolderReplicaID,
		arg.PushToken,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const listActiveLeases = `-- name: ListActiveLeases :many
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, l.agent_state_digest, l.agent_state_size, l.agent_state_format, l.agent_session_id, l.agent_state_generation, l.expires_at, l.extras_digest, l.extras_size, l.extras_format, l.extras_generation, w.name AS workspace_name, r.name AS holder_name,
       r.opencode_url AS holder_opencode_url, r.workspaces_dir AS holder_workspaces_dir
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
LEFT JOIN replicas r ON r.id = l.holder_replica_id
WHERE w.archived_at IS NULL
ORDER BY w.name, l.branch
`

type ListActiveLeasesRow struct {
	ID                   int64          `json:"id"`
	WorkspaceID          int64          `json:"workspace_id"`
	Branch               string         `json:"branch"`
	HolderReplicaID      sql.NullInt64  `json:"holder_replica_id"`
	Generation           int64          `json:"generation"`
	State                string         `json:"state"`
	SnapshotCommit       sql.NullString `json:"snapshot_commit"`
	BaseCommit           sql.NullString `json:"base_commit"`
	PushToken            sql.NullString `json:"push_token"`
	UpdatedAt            string         `json:"updated_at"`
	AgentStateDigest     sql.NullString `json:"agent_state_digest"`
	AgentStateSize       sql.NullInt64  `json:"agent_state_size"`
	AgentStateFormat     sql.NullString `json:"agent_state_format"`
	AgentSessionID       sql.NullString `json:"agent_session_id"`
	AgentStateGeneration sql.NullInt64  `json:"agent_state_generation"`
	ExpiresAt            sql.NullInt64  `json:"expires_at"`
	ExtrasDigest         sql.NullString `json:"extras_digest"`
	ExtrasSize           sql.NullInt64  `json:"extras_size"`
	ExtrasFormat         sql.NullString `json:"extras_format"`
	ExtrasGeneration     sql.NullInt64  `json:"extras_generation"`
	WorkspaceName        string         `json:"workspace_name"`
	HolderName           sql.NullString `json:"holder_name"`
	HolderOpencodeUrl    sql.NullString `json:"holder_opencode_url"`
	HolderWorkspacesDir  sql.NullString `json:"holder_workspaces_dir"`
}

func (q *Queries) ListActiveLeases(ctx context.Context) ([]ListActiveLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLeasesRow
	for rows.Next() {
		var i ListActiveLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.HolderReplicaID,
			&i.Generation,
			&i.State,
			&i.SnapshotCommit,
			&i.BaseCommit,
			&i.PushToken,
			&i.UpdatedAt,
			&i.AgentStateDigest,
			&i.AgentStateSize,
			&i.AgentStateFormat,
			&i.AgentSessionID,
			&i.AgentStateGeneration,
			&i.ExpiresAt,
			&i.ExtrasDigest,
			&i.ExtrasSize,
			&i.ExtrasFormat,
			&i.ExtrasGeneration,
			&i.WorkspaceName,
			&i.HolderName,
			&i.HolderOpencodeUrl,
			&i.HolderWorkspacesDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllLeases = `-- name: ListAllLeases :many
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, l.agent_state_digest, l.agent_state_size, l.agent_state_format, l.agent_session_id, l.agent_state_generation, l.expires_at, l.extras_digest, l.extras_size, l.extras_format, l.extras_generation, w.name AS workspace_name, r.name AS holder_name,
       r.opencode_url AS holder_opencode_url, r.workspaces_dir AS holder_workspaces_dir
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
LEFT JOIN replicas r ON r.id = l.holder_replica_id
ORDER BY w.name, l.branch
`

type ListAllLeasesRow struct {
	ID                   int64          `json:"id"`
	WorkspaceID          int64          `json:"workspace_id"`
	Branch               string         `json:"branch"`
	HolderReplicaID      sql.NullInt64  `json:"holder_replica_id"`
	Generation           int64          `json:"generation"`
	State                string         `json:"state"`
	SnapshotCommit       sql.NullString `json:"snapshot_commit"`
	BaseCommit           sql.NullString `json:"base_commit"`
	PushToken            sql.NullString `json:"push_token"`
	UpdatedAt            string         `json:"updated_at"`
	AgentStateDigest     sql.NullString `json:"agent_state_digest"`
	AgentStateSize       sql.NullInt64  `json:"agent_state_size"`
	AgentStateFormat     sql.NullString `json:"agent_state_format"`
	AgentSessionID       sql.NullString `json:"agent_session_id"`
	AgentStateGeneration sql.NullInt64  `json:"agent_state_generation"`
	ExpiresAt            sql.NullInt64  `json:"expires_at"`
	ExtrasDigest         sql.NullString `json:"extras_digest"`
	ExtrasSize           sql.NullInt64  `json:"extras_size"`
	ExtrasFormat         sql.NullString `json:"extras_format"`
	ExtrasGeneration     sql.NullInt64  `json:"extras_generation"`
	WorkspaceName        string         `json:"workspace_name"`
	HolderName           sql.NullString `json:"holder_name"`
	HolderOpencodeUrl    sql.NullString `json:"holder_opencode_url"`
	HolderWorkspacesDir  sql.NullString `json:"holder_workspaces_dir"`
}

func (q *Queries) ListAllLeases(ctx context.Context) ([]ListAllLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLeasesRow
	for rows.Next() {
		var i ListAllLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.HolderReplicaID,
			&i.Generation,
			&i.State,
			&i.SnapshotCommit,
			&i.BaseCommit,
			&i.PushToken,
			&i.UpdatedAt,
			&i.AgentStateDigest,
			&i.AgentStateSize,
			&i.AgentStateFormat,
			&i.AgentSessionID,
			&i.AgentStateGeneration,
			&i.ExpiresAt,
			&i.ExtrasDigest,
			&i.ExtrasSize,
			&i.ExtrasFormat,
			&i.ExtrasGeneration,
			&i.WorkspaceName,
			&i.HolderName,
			&i.HolderOpencodeUrl,
			&i.HolderWorkspacesDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkspaces = `-- name: ListAllWorkspaces :many
SELECT id, name, default_branch, created_at, archived_at FROM workspaces ORDER BY name
`

func (q *Queries) ListAllWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesByWorkspace = `-- name: ListLeasesByWorkspace :many
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, l.agent_state_digest, l.agent_state_size, l.agent_state_format, l.agent_session_id, l.agent_state_generation, l.expires_at, l.extras_digest, l.extras_size, l.extras_format, l.extras_generation, w.name AS workspace_name, r.name AS holder_name,
       r.opencode_url AS holder_opencode_url, r.workspaces_dir AS holder_workspaces_dir
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
LEFT JOIN replicas r ON r.id = l.holder_replica_id
WHERE l.workspace_id = ?
ORDER BY l.branch
`

type ListLeasesByWorkspaceRow struct {
	ID                   int64          `json:"id"`
	WorkspaceID          int64          `json:"workspace_id"`
	Branch               string         `json:"branch"`
	HolderReplicaID      sql.NullInt64  `json:"holder_replica_id"`
	Generation           int64          `json:"generation"`
	State                string         `json:"state"`
	SnapshotCommit       sql.NullString `json:"snapshot_commit"`
	BaseCommit           sql.NullString `json:"base_commit"`
	PushToken            sql.NullString `json:"push_token"`
	UpdatedAt            string         `json:"updated_at"`
	AgentStateDigest     sql.NullString `json:"agent_state_digest"`
	AgentStateSize       sql.NullInt64  `json:"agent_state_size"`
	AgentStateFormat     sql.NullString `json:"agent_state_format"`
	AgentSessionID       sql.NullString `json:"agent_session_id"`
	AgentStateGeneration sql.NullInt64  `json:"agent_state_generation"`
	ExpiresAt            sql.NullInt64  `json:"expires_at"`
	ExtrasDigest         sql.NullString `json:"extras_digest"`
	ExtrasSize           sql.NullInt64  `json:"extras_size"`
	ExtrasFormat         sql.NullString `json:"extras_format"`
	ExtrasGeneration     sql.NullInt64  `json:"extras_generation"`
	WorkspaceName        string         `json:"workspace_name"`
	HolderName           sql.NullString `json:"holder_name"`
	HolderOpencodeUrl    sql.NullString `json:"holder_opencode_url"`
	HolderWorkspacesDir  sql.NullString `json:"holder_workspaces_dir"`
}

func (q *Queries) ListLeasesByWorkspace(ctx context.Context, workspaceID int64) ([]ListLeasesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeasesByWorkspaceRow
	for rows.Next() {
		var i ListLeasesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.HolderReplicaID,
			&i.Generation,
			&i.State,
			&i.SnapshotCommit,
			&i.BaseCommit,
			&i.PushToken,
			&i.UpdatedAt,
			&i.AgentStateDigest,
			&i.AgentStateSize,
			&i.AgentStateFormat,
			&i.AgentSessionID,
			&i.AgentStateGeneration,
			&i.ExpiresAt,
			&i.ExtrasDigest,
			&i.ExtrasSize,
			&i.ExtrasFormat,
			&i.ExtrasGeneration,
			&i.WorkspaceName,
			&i.HolderName,
			&i.HolderOpencodeUrl,
			&i.HolderWorkspacesDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicas = `-- name: ListReplicas :many
SELECT id, name, created_at, last_seen_at, opencode_url, workspaces_dir FROM replicas ORDER BY name
`

func (q *Queries) ListReplicas(ctx context.Context) ([]Replica, error) {
	rows, err := q.db.QueryContext(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Replica
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.OpencodeUrl,
			&i.WorkspacesDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, default_branch, created_at, archived_at FROM workspaces WHERE archived_at IS NULL ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLease = `-- name: ReleaseLease :one
UPDATE leases
SET state = 'released',
    push_token = NULL,
    snapshot_commit = ?,
    base_commit = ?,
    agent_state_digest = ?,
    agent_state_size = ?,
    agent_state_format = ?,
    agent_session_id = ?,
    agent_state_generation = ?,
    extras_digest = ?,
    extras_size = ?,
    extras_format = ?,
    extras_generation = ?,
    expires_at = NULL,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation
`

type ReleaseLeaseParams struct {
	SnapshotCommit       sql.NullString `json:"snapshot_commit"`
	BaseCommit           sql.NullString `json:"base_commit"`
	AgentStateDigest     sql.NullString `json:"agent_state_digest"`
	AgentStateSize       sql.NullInt64  `json:"agent_state_size"`
	AgentStateFormat     sql.NullString `json:"agent_state_format"`
	AgentSessionID       sql.NullString `json:"agent_session_id"`
	AgentStateGeneration sql.NullInt64  `json:"agent_state_generation"`
	ExtrasDigest         sql.NullString `json:"extras_digest"`
	ExtrasSize           sql.NullInt64  `json:"extras_size"`
	ExtrasFormat         sql.NullString `json:"extras_format"`
	ExtrasGeneration     sql.NullInt64  `json:"extras_generation"`
	ID                   int64          `json:"id"`
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, releaseLease,
		arg.SnapshotCommit,
		arg.BaseCommit,
		arg.AgentStateDigest,
		arg.AgentStateSize,
		arg.AgentStateFormat,
		arg.AgentSessionID,
		arg.AgentStateGeneration,
		arg.ExtrasDigest,
		arg.ExtrasSize,
		arg.ExtrasFormat,
		arg.ExtrasGeneration,
		arg.ID,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const renewLease = `-- name: RenewLease :one
UPDATE leases
SET expires_at = ?1
WHERE id = ?2
  AND holder_replica_id = ?3
  AND generation = ?4
  AND push_token = ?5
  AND state = 'held'
  AND (expires_at IS NULL OR expires_at > ?6)
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation
`

type RenewLeaseParams struct {
	NewExpiresAt    sql.NullInt64  `json:"new_expires_at"`
	ID              int64          `json:"id"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	Generation      int64          `json:"generation"`
	PushToken       sql.NullString `json:"push_token"`
	Now             sql.NullInt64  `json:"now"`
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, renewLease,
		arg.NewExpiresAt,
		arg.ID,
		arg.HolderReplicaID,
		arg.Generation,
		arg.PushToken,
		arg.Now,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const renewLeaseByPushToken = `-- name: RenewLeaseByPushToken :one
UPDATE leases
SET expires_at = ?1
WHERE push_token = ?2
  AND state = 'held'
  AND (expires_at IS NULL OR expires_at > ?3)
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at, agent_state_digest, agent_state_size, agent_state_format, agent_session_id, agent_state_generation, expires_at, extras_digest, extras_size, extras_format, extras_generation
`

type RenewLeaseByPushTokenParams struct {
	NewExpiresAt sql.NullInt64  `json:"new_expires_at"`
	PushToken    sql.NullString `json:"push_token"`
	Now          sql.NullInt64  `json:"now"`
}

func (q *Queries) RenewLeaseByPushToken(ctx context.Context, arg RenewLeaseByPushTokenParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, renewLeaseByPushToken, arg.NewExpiresAt, arg.PushToken, arg.Now)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.AgentStateDigest,
		&i.AgentStateSize,
		&i.AgentStateFormat,
		&i.AgentSessionID,
		&i.AgentStateGeneration,
		&i.ExpiresAt,
		&i.ExtrasDigest,
		&i.ExtrasSize,
		&i.ExtrasFormat,
		&i.ExtrasGeneration,
	)
	return i, err
}

const restoreWorkspace = `-- name: RestoreWorkspace :one
UPDATE workspaces SET archived_at = NULL WHERE id = ? RETURNING id, name, default_branch, created_at, archived_at
`

func (q *Queries) RestoreWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, restoreWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertReplica = `-- name: UpsertReplica :one
INSERT INTO replicas (name, last_seen_at, opencode_url, workspaces_dir)
VALUES (?, datetime('now'), ?, ?)
ON CONFLICT (name) DO UPDATE SET
    last_seen_at = datetime('now'),
    opencode_url = CASE WHEN excluded.opencode_url != '' THEN excluded.opencode_url ELSE replicas.opencode_url END,
    workspaces_dir = CASE WHEN excluded.workspaces_dir != '' THEN excluded.workspaces_dir ELSE replicas.workspaces_dir END
RETURNING id, name, created_at, last_seen_at, opencode_url, workspaces_dir
`

type UpsertReplicaParams struct {
	Name          string `json:"name"`
	OpencodeUrl   string `json:"opencode_url"`
	WorkspacesDir string `json:"workspaces_dir"`
}

func (q *Queries) UpsertReplica(ctx context.Context, arg UpsertReplicaParams) (Replica, error) {
	row := q.db.QueryRowContext(ctx, upsertReplica, arg.Name, arg.OpencodeUrl, arg.WorkspacesDir)
	var i Replica
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.OpencodeUrl,
		&i.WorkspacesDir,
	)
	return i, err
}
