// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createHeldLease = `-- name: CreateHeldLease :one
INSERT INTO leases (workspace_id, branch, holder_replica_id, generation, state, push_token)
VALUES (?, ?, ?, 1, 'held', ?)
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at
`

type CreateHeldLeaseParams struct {
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	PushToken       sql.NullString `json:"push_token"`
}

func (q *Queries) CreateHeldLease(ctx context.Context, arg CreateHeldLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, createHeldLease,
		arg.WorkspaceID,
		arg.Branch,
		arg.HolderReplicaID,
		arg.PushToken,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, default_branch)
VALUES (?, ?)
RETURNING id, name, default_branch, created_at
`

type CreateWorkspaceParams struct {
	Name          string `json:"name"`
	DefaultBranch string `json:"default_branch"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.DefaultBranch)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const getHeldLeaseByPushToken = `-- name: GetHeldLeaseByPushToken :one
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, w.name AS workspace_name
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
WHERE l.push_token = ? AND l.state = 'held'
`

type GetHeldLeaseByPushTokenRow struct {
	ID              int64          `json:"id"`
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	Generation      int64          `json:"generation"`
	State           string         `json:"state"`
	SnapshotCommit  sql.NullString `json:"snapshot_commit"`
	BaseCommit      sql.NullString `json:"base_commit"`
	PushToken       sql.NullString `json:"push_token"`
	UpdatedAt       string         `json:"updated_at"`
	WorkspaceName   string         `json:"workspace_name"`
}

func (q *Queries) GetHeldLeaseByPushToken(ctx context.Context, pushToken sql.NullString) (GetHeldLeaseByPushTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getHeldLeaseByPushToken, pushToken)
	var i GetHeldLeaseByPushTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
		&i.WorkspaceName,
	)
	return i, err
}

const getLease = `-- name: GetLease :one
SELECT id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at FROM leases WHERE workspace_id = ? AND branch = ?
`

type GetLeaseParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Branch      string `json:"branch"`
}

func (q *Queries) GetLease(ctx context.Context, arg GetLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLease, arg.WorkspaceID, arg.Branch)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, default_branch, created_at FROM workspaces WHERE name = ?
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const grantLease = `-- name: GrantLease :one
UPDATE leases
SET holder_replica_id = ?,
    generation = generation + 1,
    state = 'held',
    push_token = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at
`

type GrantLeaseParams struct {
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	PushToken       sql.NullString `json:"push_token"`
	ID              int64          `json:"id"`
}

func (q *Queries) GrantLease(ctx context.Context, arg GrantLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, grantLease, arg.HolderReplicaID, arg.PushToken, arg.ID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLeases = `-- name: ListAllLeases :many
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, w.name AS workspace_name, r.name AS holder_name
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
LEFT JOIN replicas r ON r.id = l.holder_replica_id
ORDER BY w.name, l.branch
`

type ListAllLeasesRow struct {
	ID              int64          `json:"id"`
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	Generation      int64          `json:"generation"`
	State           string         `json:"state"`
	SnapshotCommit  sql.NullString `json:"snapshot_commit"`
	BaseCommit      sql.NullString `json:"base_commit"`
	PushToken       sql.NullString `json:"push_token"`
	UpdatedAt       string         `json:"updated_at"`
	WorkspaceName   string         `json:"workspace_name"`
	HolderName      sql.NullString `json:"holder_name"`
}

func (q *Queries) ListAllLeases(ctx context.Context) ([]ListAllLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLeasesRow
	for rows.Next() {
		var i ListAllLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.HolderReplicaID,
			&i.Generation,
			&i.State,
			&i.SnapshotCommit,
			&i.BaseCommit,
			&i.PushToken,
			&i.UpdatedAt,
			&i.WorkspaceName,
			&i.HolderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesByWorkspace = `-- name: ListLeasesByWorkspace :many
SELECT l.id, l.workspace_id, l.branch, l.holder_replica_id, l.generation, l.state, l.snapshot_commit, l.base_commit, l.push_token, l.updated_at, w.name AS workspace_name, r.name AS holder_name
FROM leases l
JOIN workspaces w ON w.id = l.workspace_id
LEFT JOIN replicas r ON r.id = l.holder_replica_id
WHERE l.workspace_id = ?
ORDER BY l.branch
`

type ListLeasesByWorkspaceRow struct {
	ID              int64          `json:"id"`
	WorkspaceID     int64          `json:"workspace_id"`
	Branch          string         `json:"branch"`
	HolderReplicaID sql.NullInt64  `json:"holder_replica_id"`
	Generation      int64          `json:"generation"`
	State           string         `json:"state"`
	SnapshotCommit  sql.NullString `json:"snapshot_commit"`
	BaseCommit      sql.NullString `json:"base_commit"`
	PushToken       sql.NullString `json:"push_token"`
	UpdatedAt       string         `json:"updated_at"`
	WorkspaceName   string         `json:"workspace_name"`
	HolderName      sql.NullString `json:"holder_name"`
}

func (q *Queries) ListLeasesByWorkspace(ctx context.Context, workspaceID int64) ([]ListLeasesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeasesByWorkspaceRow
	for rows.Next() {
		var i ListLeasesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.HolderReplicaID,
			&i.Generation,
			&i.State,
			&i.SnapshotCommit,
			&i.BaseCommit,
			&i.PushToken,
			&i.UpdatedAt,
			&i.WorkspaceName,
			&i.HolderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, default_branch, created_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultBranch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLease = `-- name: ReleaseLease :one
UPDATE leases
SET state = 'released',
    push_token = NULL,
    snapshot_commit = ?,
    base_commit = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, branch, holder_replica_id, generation, state, snapshot_commit, base_commit, push_token, updated_at
`

type ReleaseLeaseParams struct {
	SnapshotCommit sql.NullString `json:"snapshot_commit"`
	BaseCommit     sql.NullString `json:"base_commit"`
	ID             int64          `json:"id"`
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, releaseLease, arg.SnapshotCommit, arg.BaseCommit, arg.ID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.HolderReplicaID,
		&i.Generation,
		&i.State,
		&i.SnapshotCommit,
		&i.BaseCommit,
		&i.PushToken,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReplica = `-- name: UpsertReplica :one
INSERT INTO replicas (name, last_seen_at)
VALUES (?, datetime('now'))
ON CONFLICT (name) DO UPDATE SET last_seen_at = datetime('now')
RETURNING id, name, created_at, last_seen_at
`

func (q *Queries) UpsertReplica(ctx context.Context, name string) (Replica, error) {
	row := q.db.QueryRowContext(ctx, upsertReplica, name)
	var i Replica
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
